// Vue-Jobs/src/components/Navbar.vue
<script setup>
import logo from "@/assets/img/logo.png";
import NavItem from "@/components/buttons/NavbarItem.vue";
import { onMounted, reactive } from "vue";
import { RouterLink, useRoute } from "vue-router";

const isActiveLink = (routePath) => {
  const route = useRoute();
  return route.path.toLowerCase() === routePath;
};

const token = localStorage.getItem("token");
let user = reactive({
  firstName: "Guest",
});

onMounted(async () => {
  if (token) {
    user = JSON.parse(localStorage.getItem("token"));
  }

  //app.config.globalProperties.$testFunction();
});
</script>
<template>
  <nav class="bg-sky-300 border-b border-sky-900">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="flex h-20 items-center justify-between">
        <div
          class="flex flex-1 items-center justify-center md:items-stretch md:justify-start"
        >
          <!-- Logo -->
          <RouterLink class="flex flex-shrink-0 items-center mr-4" to="/">
            <img class="h-10 w-auto" :src="logo" alt="Vue Jobs" />
            <span class="hidden md:block text-white text-2xl font-bold ml-2"
              >Vue Jobs</span
            >
          </RouterLink>
          <div class="md:ml-auto">
            <div class="flex space-x-2">
              <NavItem to="/">Home</NavItem>
              <NavItem to="/jobs">Jobs</NavItem>
              <NavItem to="/dashboard">Dashboard</NavItem>
              <div class="px-3 py-2">
                Welcome, {{ $store.state.user.firstName }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</template>

// React-Stocks/src/Components/NavBar/Navbar.tsx
import { Link } from "react-router-dom";
import logo from "./logo.png";

interface Props {}

const Navbar = ({}: Props) => {
  return (
    <nav className="relative container mx-auto p-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-20">
          <Link to="/">
            <img src={logo} alt="Company Logo" />
          </Link>
          <div className="hidden font-bold lg:flex">
            <Link to="/search" className="text-black hover:text-darkBlue">
              Dashboard
            </Link>
          </div>
        </div>
        <div className="hidden lg:flex items-center space-x-6 text-back">
          <div className="hover:text-darkBlue">Login</div>
          <a
            href=""
            className="px-8 py-3 font-bold rounded text-white bg-lightGreen hover:opacity-70"
          >
            Signup
          </a>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
